# 'name' specifies the workflow name
name: A workflow for my Hello world file

# 'on' specifies the type of event to listen for and whose occurence will trigger the workflow
on: push

# A Github Workflow comprises one or more jobs
# 'jobs' specify a series of steps
jobs:
  build: 
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
